version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://soundparty:soundparty@db:5432/soundparty
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - soundparty-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=soundparty
      - POSTGRES_PASSWORD=soundparty
      - POSTGRES_DB=soundparty
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - soundparty-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@soundparty.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - soundparty-network

networks:
  soundparty-network:
    driver: bridge

volumes:
  postgres_data: 